export interface Subsection {
    level: number;
    title: string;
    content: string[];
    codeBlocks?: Array<{language: string; code: string}>;
}

export interface HeaderSection {
    title: string;
    description: string[];
    criticalNotices: string[];
    subsections: Subsection[];
}

export interface ParsedHeader {
    documentTitle: string;
    globalCritical: string[];
    autoGenerated: boolean;
    sections: HeaderSection[];
}

/**
 * Extracts the documentation header from raw content.
 * Header is everything before the first "# components/" heading.
 */
export function extractHeaderContent(rawContent: string): string {
    const lines = rawContent.split(/\r?\n/);
    const headerLines: string[] = [];

    for (const line of lines) {
        if (/^#\s+components\//.test(line)) {
            break;
        }

        headerLines.push(line);
    }

    return headerLines.join('\n').trim();
}

/**
 * Finds the line number where components section starts.
 */
export function findComponentsSectionStart(rawContent: string): number {
    const lines = rawContent.split(/\r?\n/);

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];

        if (line && /^#\s+components\//.test(line)) {
            return i;
        }
    }

    return lines.length;
}

/**
 * Parses code blocks from content lines.
 */
function extractCodeBlocks(content: string): Array<{language: string; code: string}> {
    const codeBlocks: Array<{language: string; code: string}> = [];
    const lines = content.split('\n');
    let inCodeBlock = false;
    let currentLang = '';
    let currentCode: string[] = [];

    for (const line of lines) {
        if (line.startsWith('```')) {
            if (inCodeBlock) {
                // End of code block
                codeBlocks.push({
                    language: currentLang,
                    code: currentCode.join('\n').trim(),
                });
                currentCode = [];
                inCodeBlock = false;
            } else {
                // Start of code block
                currentLang = line.slice(3).trim() || 'plaintext';
                inCodeBlock = true;
            }
        } else if (inCodeBlock) {
            currentCode.push(line);
        }
    }

    return codeBlocks;
}

/**
 * Extracts plain text content (removes markdown formatting, code blocks, etc).
 */
function extractPlainContent(content: string): string[] {
    const lines = content.split('\n');
    const plainLines: string[] = [];
    let inCodeBlock = false;

    for (const line of lines) {
        // Skip code blocks
        if (line.startsWith('```')) {
            inCodeBlock = !inCodeBlock;
            continue;
        }

        if (inCodeBlock) {
            continue;
        }

        // Skip empty lines
        if (!line.trim()) {
            continue;
        }

        // Skip markdown headings (they're already captured)
        if (/^#{1,6}\s+/.test(line)) {
            continue;
        }

        // Skip horizontal rules
        if (/^---+\s*$/.test(line)) {
            continue;
        }

        // Skip blockquotes with **Critical** or **Auto-generated** (already extracted)
        if (line.includes('**Critical**:') || line.includes('**Auto-generated**:')) {
            continue;
        }

        // Clean up other blockquotes
        let cleaned = line.replace(/^>\s*/, '').trim();

        // Remove bold/italic markers
        cleaned = cleaned.replaceAll(/\*\*([^*]+)\*\*/g, '$1');
        cleaned = cleaned.replaceAll(/\*([^*]+)\*/g, '$1');

        // Remove inline code markers
        cleaned = cleaned.replaceAll(/`([^`]+)`/g, '$1');

        if (cleaned) {
            plainLines.push(cleaned);
        }
    }

    return plainLines;
}

/**
 * Parses a section into structured data.
 */
function parseSection(content: string): HeaderSection {
    const lines = content.split('\n');
    const subsections: Subsection[] = [];
    const description: string[] = [];
    const criticalNotices: string[] = [];
    let title = '';

    // Find all headings
    const headings: Array<{line: number; level: number; title: string}> = [];

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];

        if (!line) {
            continue;
        }

        // Extract title from first heading
        const h1Match = /^#\s+([^#].+)$/.exec(line);

        if (h1Match?.[1] && !title) {
            title = h1Match[1].trim();
            headings.push({line: i, level: 1, title: h1Match[1].trim()});
            continue;
        }

        // Extract subsections (##, ###, etc)
        const hMatch = /^(#{2,6})\s+(.+)$/.exec(line);

        if (hMatch?.[1] && hMatch[2]) {
            const level = hMatch[1].length;

            headings.push({line: i, level, title: hMatch[2].trim()});
        }

        // Extract critical notices
        if (line.startsWith('> **Critical**:')) {
            const notice = line.replace(/^>\s*\*\*Critical\*\*:\s*/, '').trim();

            if (notice) {
                criticalNotices.push(notice);
            }
        }
    }

    // Extract description (content before first subsection)
    if (headings.length > 0 && headings[0]) {
        const firstSubsectionLine = headings.find((h) => h.level > 1)?.line;
        const descEnd = firstSubsectionLine ?? lines.length;
        const descContent = lines.slice(headings[0].line + 1, descEnd).join('\n');

        description.push(...extractPlainContent(descContent));
    }

    // Parse subsections
    for (let i = 1; i < headings.length; i++) {
        const current = headings[i];

        if (!current) {
            continue;
        }

        const start = current.line;
        const end = headings[i + 1]?.line ?? lines.length;
        const subsectionContent = lines.slice(start + 1, end).join('\n');

        const plainContent = extractPlainContent(subsectionContent);
        const codeBlocks = extractCodeBlocks(subsectionContent);

        subsections.push({
            level: current.level,
            title: current.title,
            content: plainContent,
            codeBlocks: codeBlocks.length > 0 ? codeBlocks : undefined,
        });
    }

    return {
        title,
        description,
        criticalNotices,
        subsections,
    };
}

/**
 * Parses the header content into fully structured JSON.
 */
export function parseHeaderSections(headerContent: string): ParsedHeader {
    const lines = headerContent.split(/\r?\n/);
    const sections: HeaderSection[] = [];
    const globalCritical: string[] = [];
    let autoGenerated = false;
    let documentTitle = 'Taiga UI Documentation';

    // Find main sections (level-1 headings)
    const sectionIndices: Array<{line: number; title: string}> = [];

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];

        if (!line) {
            continue;
        }

        // Level-1 heading
        const h1Match = /^#\s+([^#].+)$/.exec(line);

        if (h1Match?.[1]) {
            sectionIndices.push({
                line: i,
                title: h1Match[1].trim(),
            });
        }

        // Extract global critical notices (from the very beginning)
        if (i < 10 && line.startsWith('> **Critical**:')) {
            const notice = line.replace(/^>\s*\*\*Critical\*\*:\s*/, '').trim();

            if (notice) {
                globalCritical.push(notice);
            }
        }

        // Check for auto-generated marker
        if (i < 10 && line.includes('Auto-generated')) {
            autoGenerated = true;
        }
    }

    // Use first section title as document title if available
    if (sectionIndices.length > 0 && sectionIndices[0]) {
        documentTitle = sectionIndices[0].title;
    }

    // Parse each section
    for (let i = 0; i < sectionIndices.length; i++) {
        const currentSection = sectionIndices[i];

        if (!currentSection) {
            continue;
        }

        const start = currentSection.line;
        const end = sectionIndices[i + 1]?.line ?? lines.length;
        const sectionContent = lines.slice(start, end).join('\n');

        const parsedSection = parseSection(sectionContent);

        sections.push(parsedSection);
    }

    return {
        documentTitle,
        globalCritical,
        autoGenerated,
        sections,
    };
}
