import {type McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import {z} from 'zod';

import {ensureSourceLoaded} from '../server/fetch.js';
import {state} from '../server/server.js';
import {
    type HeaderSection,
    parseHeaderSections,
    type Subsection,
} from '../utils/extract-header.js';

interface OverviewOutput {
    documentTitle: string;
    globalCritical: string[];
    autoGenerated: boolean;
    sections: Array<{
        title: string;
        description: string[];
        criticalNotices: string[];
        subsections: Array<{
            level: number;
            title: string;
            content: string[];
            codeBlocks?: Array<{language: string; code: string}>;
        }>;
    }>;
    totalComponents: number;
    sourceUrl?: string;
    [key: string]: unknown;
}

export function registerGetOverviewTool(server: McpServer): void {
    server.registerTool(
        'get_overview',
        {
            title: 'Get Documentation Overview',
            description:
                'Retrieve the fully structured documentation header as JSON. Returns hierarchical sections with parsed content (no raw markdown). Each section contains: title, description, critical notices, and subsections with their content and code blocks.',
            inputSchema: z.object({}).strict(),
            outputSchema: {
                documentTitle: z.string(),
                globalCritical: z.array(z.string()),
                autoGenerated: z.boolean(),
                sections: z.array(
                    z.object({
                        title: z.string(),
                        description: z.array(z.string()),
                        criticalNotices: z.array(z.string()),
                        subsections: z.array(
                            z.object({
                                level: z.number(),
                                title: z.string(),
                                content: z.array(z.string()),
                                codeBlocks: z
                                    .array(
                                        z.object({
                                            language: z.string(),
                                            code: z.string(),
                                        }),
                                    )
                                    .optional(),
                            }),
                        ),
                    }),
                ),
                totalComponents: z.number(),
                sourceUrl: z.string().optional(),
            },
        },
        async () => {
            await ensureSourceLoaded();

            const headerInfo = state.headerContent
                ? parseHeaderSections(state.headerContent)
                : {
                      documentTitle: 'Taiga UI Documentation',
                      globalCritical: [],
                      autoGenerated: false,
                      sections: [],
                  };

            const output: OverviewOutput = {
                documentTitle: headerInfo.documentTitle,
                globalCritical: headerInfo.globalCritical,
                autoGenerated: headerInfo.autoGenerated,
                sections: headerInfo.sections.map((section: HeaderSection) => ({
                    title: section.title,
                    description: section.description,
                    criticalNotices: section.criticalNotices,
                    subsections: section.subsections.map((sub: Subsection) => ({
                        level: sub.level,
                        title: sub.title,
                        content: sub.content,
                        codeBlocks: sub.codeBlocks,
                    })),
                })),
                totalComponents: state.sections.length,
                sourceUrl: state.sourceUrl,
            };

            return {
                content: [
                    {
                        type: 'text',
                        text: JSON.stringify(output, null, 2),
                    },
                ],
                structuredContent: output,
            };
        },
    );
}
